# @package _global_

defaults:
  - model: linear_bert
  - dataset: scene
  - processing: linear_bert

input: null
checkpoint: null

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}